# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
#  pip_install: true
  setup_py_install: true
  extra_requirements:
    - docs

sphinx:
   configuration: docs/conf.py

formats:
    - pdf
    - epub