# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: setuptools
      path: .

sphinx:
   configuration: docs/source/conf.py

formats:
    - pdf
    - epub